// All constants relataed to theses
export const MAXIMUM_THESIS_CONTENT_CHARACTERS = 30000;
export const MAXIMUM_THESIS_TITLE_CHARACTERS = 100;
export const MAXIMUM_THESIS_CONTENT_VISIBLE_LINES = 5;
export const MAXIMUM_THESIS_TITLE_VISIBLE_LINES = 1;
export const THESIS_BOX_HEIGHT = 200;